package table

import "github.com/charmbracelet/lipgloss"

// Styles contains style definitions for this list component. By default, these
// values are generated by DefaultStyles.
type Styles[T any] struct {
	Header   lipgloss.Style
    // Column is the header title of the column that the style is being applied to.
    // This is preferred over the column index as it allows us to change the column order without breaking the styles.
	Cell     func(item T, column string) lipgloss.Style
	Selected lipgloss.Style
}

// DefaultStyles returns a set of default style definitions for this table.
func DefaultStyles[T any]() Styles[T] {
	return Styles[T]{
		Selected: lipgloss.NewStyle().Bold(true).Background(lipgloss.Color("212")),
		Header:   lipgloss.NewStyle().Bold(true).Padding(0, 1),
		Cell:     func(_ T, _ string) lipgloss.Style { return lipgloss.NewStyle().Padding(0, 1) },
	}
}

